name: Issue Reply

on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Usage
        if: github.event.label.name == 'Usage' || github.event.label.name == 'Question'
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: data-view-naive
