name: Issue Open Check

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: check format
        if: (contains(github.event.issue.body, 'issue-helper') == false)
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'invalid'
          body: data-view-naive

